# 服务内配置
wls:
  swagger:
    enabled: true
    group-name: "wls-system-api"
    base-package: "plus.wls"
    title: "系统服务接口文档"
    description: "调用接口前请详细阅读文档，并遵守文档调用规范"
    version: "1.0.0"
    contact-name: "wls"
    contact-url: "plus.wls"
    contact-email: "1626961806@qq.com"

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 9700
  servlet:
    # 应用的访问路径
    context-path: /wls-system

# Spring配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wls-ry-vue?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: wls-mysql-tencent
  # redis 配置
  redis:
    # 地址
    host: localhost
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password: wlsredis
    # 连接超时时间
    timeout: 60s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 4
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 64
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms









