# Hexo Configuration
# Docs: https://hexo.io/docs/configuration.html
# Source: https://github.com/hexojs/hexo/

# 主页subtitle
subtitle:
  enable: true
  # 打字效果
  effect: true
  # 循环或者只打字一次
  loop: true
  # source调用第三方服务
  # source: false 关闭调用
  # source: 1  调用搏天api的随机语录（简体） https://api.btstu.cn/
  # source: 2  调用一言网的一句话（简体） https://hitokoto.cn/
  # source: 3  调用一句网（简体） http://yijuzhan.com/
  # source: 4  调用今日诗词（简体） https://www.jinrishici.com/
  # subtitle 会先显示 source , 再显示 sub 的内容
  source: 2
    # 如果有英文逗号' , ',请使用转义字元 &#44;
    # 如果有英文双引号' " ',请使用转义字元 &quot;
    # 开头不允许转义字元，如需要，请把整个句子用双引号包住
    # 例如 ”&quotNever put off till tomorrow what you can do today&quot"
    # 如果关闭打字效果，subtitle只会显示sub的第一行文字
    # sub:
    # - Never put off till tomorrow what you can do today
  # - 今日事&#44;今日毕

menu:
  首页: / || fas fa-home
  时间轴: /archives/ || fas fa-archive
  # 标签: /tags/ || fas fa-tags
  # 分类: /categories/ || fas fa-folder-open
  音乐: /music/ || fa-fw fas fa-music
  友链: /link/ || fas fa-link
  # 关于: /about/ || fas fa-heart

#头像
avatar:
  img: https://erectpine-blog.oss-cn-chengdu.aliyuncs.com/avatar/0a7e4f692bac5f3fc20fb1b1d71412b2.png
  # 头像会一直转圈
  effect: false

favicon: /img/favicon.png

#默认的
default_top_img: https://wls-blog-img.oss-cn-shenzhen.aliyuncs.com/wallhaven-md27xm.jpg
# if the banner of page not setting, it will show the top_img
#主页的 top_img
index_img: https://wls-blog-img.oss-cn-shenzhen.aliyuncs.com/wallhaven-ymz61d.jpg
#index_img: https://powerthunder-blog.oss-cn-chengdu.aliyuncs.com/cover/27-min.jpg
#归档页面
# archive_img: https://erectpine-blog.oss-cn-chengdu.aliyuncs.com/test/house-5651866_1920.jpg
#tag 子页面 的 默认 top_img
# tag_img: https://erectpine-blog.oss-cn-chengdu.aliyuncs.com/index/poland-1387075-640x512.jpg
#tag 子页面的 top_img，可配置每个 tag 的 top_img
# tag_per_img: https://erectpine-blog.oss-cn-chengdu.aliyuncs.com/index/sunset-fisher-poland-1567241.jpg
#category 子页面 的 默认 top_img
# category_img: https://erectpine-blog.oss-cn-chengdu.aliyuncs.com/index/after-the-silence-1545251.jpg
#category 子页面的 top_img，可配置每个 category 的 top_img
# category_per_img: https://erectpine-blog.oss-cn-chengdu.aliyuncs.com/index/night-fog-1521028-1918x1094.jpg
# top_img: https://erectpine-blog.oss-cn-chengdu.aliyuncs.com/index/poland-1387075-640x512.jpg
#background-color: rgba(0, 0, 0, 0); background-image: url("");

# 主页设置
# 默认top_img全屏，site_info在中间
# 使用默认, 都无需填写（建议默认）
index_site_info_top:  # 主页标题距离顶部距离  例如 300px/300em/300rem/10%
index_top_img_height:  #主页top_img高度 例如 300px/300em/300rem  不能使用百分比

# 加载动画 Loading Animation
preloader: true

# 音乐
aplayerInject:
  enable: true
  per_page: true

aplayer:
  meting: true
  asset_inject: false

# Inject
# Insert the code to head (before '</head>' tag) and the bottom (before '</body>' tag)
# 插入代码到头部 </head> 之前 和 底部 </body> 之前
inject:
  head:
  # - <link rel="stylesheet" href="/xxx.css">
  bottom:
    # - <script src="xxxx"></script>
#    - <script defer src="/live2d-widget/autoload.js"></script>
    - <div class="aplayer no-destroy" data-id="8049504333" "data-volume"="0.8" data-server="tencent" data-type="playlist" data-fixed="true" data-mini="true" data-listFolded="false" data-order="random" data-preload="none" data-autoplay="true" muted></div>

#pjax:
#  enable: true

social:
  fab fa-qq: http://wpa.qq.com/msgrd?v=3&uin=1626961806&site=qq&menu=yes || qq
  fab fa-github: https://erectpine.coding.net/public/wls-learn/wls-blog-page/git/files || coding
  fas fa-envelope: mailto:1626961806@qq.com || Email

aside:
  enable: true
  mobile: true # display on mobile
  position: right # left or right
  card_author:
    enable: true
    description:
    button:
      icon: fab fa-github
      text: Follow Me
      link: https://erectpine.coding.net/public/wls-learn/wls-blog-page/git/files
  card_announcement:
    enable: false
    content: This is my Blog
    sort_order:
  card_recent_post:
    enable: true
    limit: 5 # if set 0 will show all
    sort: date # date or updated
    sort_order: 10
  # card_categories:
  #   enable: true
  #   limit: 8 # if set 0 will show all
  #   expand: none # none/true/false
  #   sort_order: 20
  # card_tags:
  #   enable: true
  #   limit: 40 # if set 0 will show all
  #   color: false
  #   sort_order: 30
  card_archives:
    enable: false
    type: monthly # yearly or monthly
    format: MMMM YYYY # eg: YYYY年MM月
    order: -1 # Sort of order. 1, asc for ascending; -1, desc for descending
    limit: 8 # if set 0 will show all
    sort_order: 40
  card_webinfo:
    enable: true
    post_count: true
    last_push_date: true
    sort_order: 100

# Typewriter Effect (打字效果)
# https://github.com/disjukr/activate-power-mode
activate_power_mode:
  enable: true
  colorful: true # open particle animation (冒光特效)
  shake: false #  open shake (抖动特效)
  mobile: false

# 图片大图查看模式
fancybox: true

# Snackbar 弹窗
# https://github.com/polonel/SnackBar
# position 弹窗位置
# 可选 top-left / top-center / top-right / bottom-left / bottom-center / bottom-right
snackbar:
  enable: true
  position: bottom-left
  bg_light: '#49b1f5' #light mode时弹窗背景
  bg_dark: '#2d3035' #dark mode时弹窗背景


# 点击出现文字，文字可自行修改
ClickShowText:
  enable: true
  text:
    - I
    - LOVE
    - YOU
  fontSize: 15px
  mobile: false


# 点击出现爱心
click_heart:
  enable: true
  mobile: false

# 美化页面显示
beautify:
  enable: true
  field: site # site/post
  title-prefix-icon: '\f0c1'
  title-prefix-icon-color: "#F47466"

footer:
  # custom_text: <a href="https://beian.miit.gov.cn/#/Integrated/index"><span>蜀ICP备2020027563号-1</span></a>
  custom_text: <a target="_blank" rel="noopener" href="https://beian.miit.gov.cn/"><img class="icp-icon entered loading" src="/img/icp.png" data-ll-status="loading"><span>蜀ICP备2020027563号</span></a>


# 背景特效
canvas_nest:
  enable: true
  color: '0,0,255' #color of lines, default: '0,0,0'; RGB values: (R,G,B).(note: use ',' to separate.)
  opacity: 0.7 # the opacity of line (0~1), default: 0.5.
  zIndex: -1 # z-index property of the background, default: -1.
  count: 99 # the number of lines, default: 99.
  mobile: false # false 手机端不显示 true 手机端显示

canvas_fluttering_ribbon:
  enable: true
  mobile: false # false 手机端不显示 true 手机端显示

related_post:
  enable: true
  limit: 5 # 显示推荐文章数目
  date_type: created # or created or updated 文章日期显示创建日或者更新日

#可开启图片Figcaption描述文字显示
photofigcaption: true

# 复製的内容是否添加版权信息
copy:
  enable: true
  copyright:
    enable: true
    limit_count: 200

# 简繁转换
translate:
  enable: true
  # 默认按钮显示文字(网站是简体，应设置为'default: 繁')
  default: 简
  #网站默认语言，1: 繁体中文, 2: 简体中文
  defaultEncoding: 2
  #延迟时间,若不在前, 要设定延迟翻译时间, 如100表示100ms,默认为0
  translateDelay: 0
  #当文字是简体时，按钮显示的文字
  msgToTraditionalChinese: "繁"
  #当文字是繁体时，按钮显示的文字
  msgToSimplifiedChinese: "简"

# 夜间模式
darkmode:
  enable: true
  # dark mode和 light mode切换按钮
  button: true
  autoChangeMode: false

# 阅读模式
readmode: true

# Change font size
change_font_size: true

# 访问人数 busuanzi (UV 和 PV)
busuanzi:
  site_uv: true
  site_pv: true
  page_pv: true

# 网页已运行时间
runtimeshow:
  enable: true
  publish_date: 1/10/2020 00:00:00
  ##网页开通时间
  #格式: 月/日/年 时间
  #也可以写成 年/月/日 时间

# 在侧边栏显示最新评论板块
newest_comments:
  enable: false
  limit: 6
  avatar: true
  leancloud:
    enable: false
    appId: # leancloud application app id
    appKey: # leancloud application app key
    serverURL: # This configuration is suitable for domestic custom domain name users, overseas version will be automatically detected (no need to manually fill in)
    default_avatar: robohash # mp/identicon/monsterid/wavatar/retro/robohash/blank
  github_issues:
    enable: true
    repo:
  disqus:
    enable: false
    forum:
    api_key:

# 评论
comments:
  # Up to two comments system, the first will be shown as default
  # Choose: Disqus/Disqusjs/Livere/Gitalk/Valine/Utterances/Facebook Comments
  use:
    - Valine
  text: true # Display the comment name next to the button
  # lazyload: The comment system will be load when comment element enters the browser's viewport.
  # If you set it to true, the comment count will be invalid
  lazyload: true
  count: true # Display comment count in top_img

# # 在綫聊天
# chat_btn: true
# chat_hide_show: true

# 网站验证 搜索引擎收录网站
#google_site_verification:
## Bing Webmaster tools verification setting
## See: https://www.bing.com/webmaster/
#bing_site_verification:
## Baidu Webmaster tools verification setting
## See: https://ziyuan.baidu.com/site/
#baidu_site_verification:
## 360 Webmaster tools verification setting
## see http://zhanzhang.so.com/
#qihu_site_verification:
## Yandex Webmaster tools verification setting
## see https://webmaster.yandex.com/
#yandex_site_verification:

# Math 数学
katex:
  enable: true
  # true 表示每一页都加载katex.js
  # false 需要时加载，须在使用的Markdown Front-matter 加上 katex: true
  per_page: false
  hide_scrollbar: true

# 图片格式 url(http://xxxxxx.com/xxx.jpg)
# 颜色（HEX值/RGB值/顔色单词/渐变色)
# 留空 不显示背景
#background: url(https://erectpine-blog.oss-cn-chengdu.aliyuncs.com/index/index.jpg)
background: ’#49B202’

# footer是否显示图片背景(与top_img一致)
footer_bg: true

#文章锚点
#开启文章锚点后，当你在文章页进行滚动时，文章链接会根据标题ID进行替换
anchor: true

# Artitalk
# see https://artitalk.js.org/
#artitalk:
#  appId: xxxxx
#  appKey: xxxxx
#  option:
#    serverURL: xxxxx
#      lang: zh

cover:
  # 是否显示文章封面
  index_enable: true
  aside_enable: true
  archives_enable: true
  # 封面显示的位置
  # 三个值可配置 left , right , both
  position: both
  # 当没有设置cover时，默认的封面显示
  default_cover:
    - https://erectpine-blog.oss-cn-chengdu.aliyuncs.com/index/night-fog-1521028-1918x1094.jpg
    - https://wls-blog-img.oss-cn-shenzhen.aliyuncs.com/v2-be9659feb3e1ec31a4bba496369662ec_r.jpg
    - https://wls-wallpaper.oss-cn-chengdu.aliyuncs.com/wallhaven-d5ojdj.jpg
    - https://wls-wallpaper.oss-cn-chengdu.aliyuncs.com/wallhaven-9mxjp8.jpg
    - https://wls-wallpaper.oss-cn-chengdu.aliyuncs.com/wallhaven-v9g1y5.jpg
    - https://wls-wallpaper.oss-cn-chengdu.aliyuncs.com/wallhaven-z8m6gj.jpg

# Replace Broken Images (替換無法顯示的圖片)
error_img:
  flink: /img/friend_404.gif
  post_page: /img/404.jpg

# A simple 404 page
error_404:
  enable: true
  subtitle: 'Page Not Found'
  background: https://i.loli.net/2020/05/19/aKOcLiyPl2JQdFD.png

post_copyright:
  enable: true
  decode: false
  license: CC BY-NC-SA 4.0
  license_url: https://creativecommons.org/licenses/by-nc-sa/4.0/

# toc:
#   enable: true
#   number: true
#   auto_open: true # auto open the sidebar

reward:
  enable: true
  QR_code:
    - img: https://erectpine-blog.oss-cn-chengdu.aliyuncs.com/money/wx-pay.jpg
      link:
      text: 微信
    - img: https://erectpine-blog.oss-cn-chengdu.aliyuncs.com/money/aliyun-pay.jpg
      link:
      text: 支付宝

post_meta:
  page:
    date_type: both # created or updated or both 主页文章日期是创建日或者更新日或都显示
    date_format: relative # date/relative 显示日期还是相对日期
    categories: true # true or false 主页是否显示分类
    tags: true # true or false 主页是否显示标籤
    label: true # true or false 显示描述性文字
    post:
      date_type: both # created or updated or both 文章页日期是创建日或者更新日或都显示
      date_format: relative # date/relative 显示日期还是相对日期
      categories: true # true or false 文章页是否显示分类
      tags: true # true or false 文章页是否显示标籤
      label: true # true or false 显示描述性文字

# 代码高亮
highlight_theme: mac light

highlight_copy: true

highlight_shrink: false

code_word_wrap: true

index_post_content:
  method: 3
  length: 500

# URL
## If your site is put in a subdirectory, set url as 'http://example.com/child' and root as '/child/'
url: http://example.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true
  trailing_html: true

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''

filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true

highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false

prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# npm uninstall hexo-helper-live2d
## https://github.com/EYHN/hexo-helper-live2d
#live2d:
#  enable: true #开关插件版看板娘
#  scriptFrom: local # 默认
#  pluginRootPath: live2dw/ # 插件在站点上的根目录(相对路径)
#  pluginJsPath: lib/ # 脚本文件相对与插件根目录路径
#  pluginModelPath: assets/ # 模型文件相对与插件根目录路径
#  # scriptFrom: jsdelivr # jsdelivr CDN
#  # scriptFrom: unpkg # unpkg CDN
#  # scriptFrom: https://cdn.jsdelivr.net/npm/live2d-widget@3.x/lib/L2Dwidget.min.js # 你的自定义 url
#  tagMode: false # 标签模式, 是否仅替换 live2d tag标签而非插入到所有页面中
#  debug: false # 调试, 是否在控制台输出日志
#  model:
#    use: live2d-widget-model-wanko # npm-module package name
#    # use: wanko # 博客根目录/live2d_models/ 下的目录名
#    # use: ./wives/wanko # 相对于博客根目录的路径
#    # use: https://cdn.jsdelivr.net/npm/live2d-widget-model-wanko@1.0.5/assets/wanko.model.json # 你的自定义 url
#  display:
#    position: left #控制看板娘位置
#    width: 150 #控制看板娘大小
#    height: 300 #控制看板娘大小
#  mobile:
#    show: true # 手机中是否展示


# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: butterfly

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repository: https://gitee.com/wls_java/wls-blog.git #Git仓库地址，:符号后为Git仓库服务器路径
  branch: master #分支，由于我们只用Git进行发布，master即可。
